WebDjProject/Controllers/RoleController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDjProject.Models;

namespace WebDjProject.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        ApplicationDbContext context;
        public RoleController()
        {
            context = new ApplicationDbContext();
        }

        // GET: Role
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                if (!isAdminUser())
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

            var Roles = context.Roles.ToList();
            return View(Roles);

        }

        public bool isAdminUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ApplicationDbContext context = new ApplicationDbContext();
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                var s = UserManager.GetRoles(user.GetUserId());
                if (s[0].ToString() == "Admin")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            return false;
        }
    }
}

WebDjProject/Controllers/UsersController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Text;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using WebDjProject.Models;

namespace WebDjProject.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ViewBag.Name = user.Name;

                ViewBag.displayMenu = "No";

                if (isAdminUser())
                {
                    ViewBag.displayMenu = "Yes";
                }
                return View();
            }
            else
            {
                ViewBag.Name = "Not Logged IN";
            }
            return View();

        }

        
        public ActionResult GetSongs()
        {
            ApplicationDbContext db = new ApplicationDbContext();

            var adminUserID = User.Identity.GetUserId();

            var premiumUsersList = db.Users.Where(u => u.Roles.Count >= 1 && u.Id != adminUserID).ToList();

            List<Playlist> premiumPlaylistsList = new List<Playlist>();

            foreach (var premiumUser in premiumUsersList)
            {
                var checkedPlaylist = db.Playlists.Where(p => p.ApplicationUserId == premiumUser.Id).First();
                
                premiumPlaylistsList.Add(checkedPlaylist);
            }

            return View(premiumPlaylistsList);
        }

        [HttpPost]
        public ActionResult SendEmails(List<int> PlaylistIDs, List<string> SongsLists)
        {
            ApplicationDbContext db = new ApplicationDbContext();

            for (int i = 0; i < PlaylistIDs.Count; i++)
            {
                var currentPlaylistID = PlaylistIDs[i];
                Playlist currentPlaylist = db.Playlists.Where(p => p.playlistId == currentPlaylistID).Single();

                var currentUser = db.Users.Where(u => u.Id == currentPlaylist.ApplicationUserId).Single();

                var userEmail = currentUser.Email;
                var userName = currentUser.UserName;
                List<string> userSongList = new List<string>(SongsLists[i].Split(",".ToCharArray()));


                SendPremiumMail(userEmail, userName, userSongList, currentPlaylist.playlistName);
            }

            Thread.Sleep(2000);
            return RedirectToAction("Index", "Home");
        }
        public void SendPremiumMail(string address, string name, List<string> Songlist, string playlistName)
        {
            // Command line argument must the the SMTP host.
            SmtpClient client = new SmtpClient();
            client.Port = 587;
            client.Host = "smtp.gmail.com";
            client.EnableSsl = true;
            client.Timeout = 10000;
            client.DeliveryMethod = SmtpDeliveryMethod.Network;
            client.UseDefaultCredentials = false;
            client.Credentials = new System.Net.NetworkCredential("webdjmessaging@gmail.com", "Carbuncle#9");

            MailMessage mm = new MailMessage(address, address, "WebDJ -- Premium Account Recommendations", "Hello " + name + "! Based on the playlist '" + playlistName + "' you made using our website, here are some songs we think you might like. \n https://open.spotify.com/track/" + Songlist[0] + " \n https://open.spotify.com/track/" + Songlist[1] + " \n https://open.spotify.com/track/" + Songlist[2] + " \n https://open.spotify.com/track/" + Songlist[3] + " \n https://open.spotify.com/track/" + Songlist[4]);
            mm.BodyEncoding = UTF8Encoding.UTF8;
            mm.DeliveryNotificationOptions = DeliveryNotificationOptions.OnFailure;

            client.Send(mm);
        }

        public bool isAdminUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ApplicationDbContext context = new ApplicationDbContext();
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                var s = UserManager.GetRoles(user.GetUserId());
                if (s[0].ToString() == "Admin")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            return false;
        }
    }
}

WebDjProject/Views/Users/GetSongs.cshtml
@model IEnumerable<WebDjProject.Models.Playlist>

@{
    ViewBag.Title = "Send out emails";
}

<h3>
    <button onclick="postTrackSets()">Send out emails to premium users.</button>
</h3>

<script src="~/Scripts/jquery-3.3.1.js"></script>
<script type="text/javascript">


    // Get the hash of the url
    const hash = window.location.hash
        .substring(1)
        .split('&')
        .reduce(function (initial, item) {
            if (item) {
                var parts = item.split('=');
                initial[parts[0]] = decodeURIComponent(parts[1]);
            }
            return initial;
        }, {});
    window.location.hash = '';

    // Set token
    let _token = hash.access_token;

    const authEndpoint = 'https://accounts.spotify.com/authorize';
    const refreshEndpoint = 'https://accounts.spotify.com/api/token'

    // Replace with your app's client ID, redirect URI and desired scopes
    const clientId = 'ddb6bd84d33c42aba1450a177ca0f23e';
    const redirectUri = 'http://localhost:53881/Users/GetSongs/';
    const clientSecret = 'd2e2b989c762414c88b6c3121dd44a65';

    const scopes = [
        'playlist-read-private',
        'user-modify-playback-state',
        'user-read-recently-played',
        'user-read-currently-playing',
        'playlist-modify-private',
        'app-remote-control',
        'playlist-modify-public',
        'user-read-birthdate',
        'user-read-playback-state',
        'user-read-email',
        'streaming',
        'user-read-private',
        'user-top-read',
        'app-remote-control'
    ];

    // If there is no token, redirect to Spotify authorization
    if (!_token) {
        window.location = `${authEndpoint}?client_id=${clientId}&redirect_uri=${redirectUri}&scope=${scopes.join('%20')}&response_type=token&show_dialog=false`;
    }

    var trackListsList = [];
    var currentTrackList = [];
    var usedTrackList = [];

    var currentPlaylistID;
    var playlistIDlist = [];

    var allTracksString;
    var recommendedTrackIDs = [];
    var recommendedTracks = [];
    var recommendedTrackIDString;

    function createRecommendedTrackLists() {

        if (_token) {

            @foreach (var item in Model)
            {
            <text>

            usedTrackList = [];
            recommendedTrackIDs = [];

            currentTrackList = getSongs('@item.spotifyPlaylistID', _token)

            if (currentTrackList.length <= 5)
            {
                for (j = 0; j < currentTrackList.length; j++)
                {
                    usedTrackList.push(currentTrackList[j])
                }
            }
            else
            {
                for (j = 0; j < 5; j++)
                {
                    usedTrackList.push(currentTrackList[j])
                }
            }
            

            allTracksString = usedTrackList.join(",")
            recommendedTracks = spotifyGetRecommendations(allTracksString, _token);

            for (d = 0; d < 5; d++) {
                recommendedTrackIDs.push(recommendedTracks[0].tracks[d].id);
            }

            currentPlaylistID = @item.playlistId
            playlistIDlist.push(currentPlaylistID);

            recommendedTrackIDString = recommendedTrackIDs.join(",")
            trackListsList.push(recommendedTrackIDString);

            </text>
            }

            //console.log(trackListsList);

        }
    }

    function spotifyGetRecommendations(tracks, authToken) {
        var recommendedTracks = [];
        $.ajax({
            url: 'https://api.spotify.com/v1/recommendations?limit=5&market=US&seed_tracks=' + tracks,
            method: "GET",
            async: false,
            headers: {
                'Authorization': 'Bearer ' + authToken,
            },
            success: function (response) {
                recommendedTracks.push(response)
            },
            error: function (response) {
            }
        });
        return recommendedTracks
    }

    function getSongs(playlistId, authToken) {
        var id = playlistId;

        var trackIDList = [];
        $.ajax({
            url: 'https://api.spotify.com/v1/playlists/' + id + '/tracks',
            method: "GET",
            async: false,
            headers: {
                'Authorization': 'Bearer ' + authToken,
                'Content-Type': 'application/json'
            },
            success: function (response) {
                for (k = 0; k < response.items.length; k++) {
                    trackIDList.push(response.items[k].track.id);
                }
            },
            error: function (response) {

            }
        });
        return trackIDList;
    }

    function postTrackSets() {
        createRecommendedTrackLists()

        var objAjax = new Object();
        objAjax.PlaylistIDs = playlistIDlist;
        objAjax.SongsLists = trackListsList;

        $.ajax('@Url.Action("SendEmails", "Users")', {
        type: 'POST',
        data: JSON.stringify(objAjax),
        contentType: "application/json",
        async: false,
        dataType: "json",
        traditional: true,
        success: function () {
            //console.log("Success!");
        },
        error: function () {
        }
        });
    }


</script>

WebDjProject/Views/Users/Index.cshtml
@{
    ViewBag.Title = "Index";
}



@if (ViewBag.displayMenu == "Yes")
{
    <h4>Welcome, Administrator.</h4>
    <div>
        <ul>
            <li>@Html.ActionLink("Manage Roles", "Index", "Role")</li>
        </ul>
    </div>
}
else
{
    <h2>  Hello <strong>@User.Identity.Name</strong>. You have reached this page in error. </h2>
}

<h2>
    @Html.ActionLink("Send out Emails", "GetSongs", "Users")
</h2>